apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend-autoscaling-label
spec:
  selector:
    matchLabels:
      project: backend
  template:
    metadata:
      labels:
        project: backend
    spec:
      containers:
        - name: backend-container
          image: cr.yandex/crp8ui9gahh6vsr4j039/app-backend:1.8

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 15