apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend-deployment-label
spec:
  selector:
    matchLabels:
      project: frontend
  template:
    metadata:
      labels:
        project: frontend
    spec:
      containers:
        - name: frontend-container
          image: cr.yandex/crp8ui9gahh6vsr4j039/app-frontend:1.1
          ports:
            - containerPort: 80