apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    env: prod
    app: main
    tier: frontend
spec:
  containers:
    - name: frontend-container
      image: cr.yandex/crp8ui9gahh6vsr4j039/app-frontend:1.1
      ports:
        - containerPort: 80

