apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend-autoscaling-label
spec:
  selector:
    matchLabels:
      project: frontend
  template:
    metadata:
      labels:
        project: frontend
    spec:
      containers:
        - name: backend-container
          image: cr.yandex/crp8ui9gahh6vsr4j039/app-frontend:1.1
          ports:
            - containerPort: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 15