apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend-autoscaling-label
spec:
  selector:
    matchLabels:
      project: backend
  template:
    metadata:
      labels:
        project: backend
    spec:
      containers:
        - name: backend-container
          image: cr.yandex/crp8ui9gahh6vsr4j039/app-backend:2.6
          ports:
            - containerPort: 4444
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 15
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service-autoscaler
  labels:
    env  : prod
    name: backend-service
spec:
  selector:
    project: backend
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 4444
      targetPort: 4444
  type: LoadBalancer