name: ITMO

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Go
      uses: actions/setup-go@v5  
      with:
        go-version: '1.22' 

    - name: List files in root
      run: ls -la

    - name: List files in backend
      run: ls -la backend

    - name: Install dependencies
      run: go mod download
      working-directory: backend

    - name: Build application
      run: go build -o request-tracker-app
      working-directory: backend

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: request-tracker-app
        path: backend/request-tracker-app
    


  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: request-tracker-app

      - name: List files after download
        run: ls -la
      - name: Set executable permission
        run: chmod +x request-tracker-app

      - name: Run server in background
        run: |
          ./request-tracker-app &
          sleep 5  # Даем серверу время на запуск

      - name: test
        run: go test ./...
        working-directory: backend
