name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod download
        working-directory: backend

      - name: Build application
        run: go build -o request-tracker-app
        working-directory: backend

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run server in background
        run: |
          ./backend/request-tracker-app &
          sleep 5  

      - name: Run tests
        run: go test ./...
        working-directory: backend

  cleanup:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Clean up untracked files
        run: git clean -fdx