name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install backend dependencies
        run: go mod download
        working-directory: backend

      - name: Run backend tests
        run: go test .
        working-directory: backend

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.1.0'

      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend

      - name: Run frontend tests
        run: npm test
        working-directory: frontend

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install backend dependencies
        run: go mod download
        working-directory: backend

      - name: Build application
        run: go build -o request-tracker-app
        working-directory: backend