name: ITMO

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Go
      uses: actions/setup-go@v5  
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: go mod download
      working-directory: backend 

    - name: Build application
      run: go build -o request-tracker-app
      working-directory: backend  

    - name: Set executable permission
      run: chmod +x backend/request-tracker-app  

    - name: Run tests on the built application
      run: |
        ./request-tracker-app test  # Запуск вашего приложения с параметром 'test'
