name: ITMO

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22rc2'

    - name: Install dependencies
      run: |
        cd backend  # Переход в каталог backend
        go mod download  # Загрузка зависимостей

    - name: Build application
      run: |
        cd backend 
        go build -o request-tracker-app 

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: request-tracker-app
        path: backend/request-tracker-app  


  test:
    runs-on: ubuntu-latest
    needs: build  
    
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3  
        with:
          name: request-tracker-app
      
      - name: Run tests
        run: |
          cd backend
          go test -v
